 1  Encoding and Decoding              21  Fare Displays
 2  Flight Availability                22  Fare Display Options 
 3  Follow-up Availability             23  Fare Notes
 4  Alternative Availability Entries   24  Itinerary Pricing           
 5  Selling from Availability          25  Pricing Options 
 6  Selling by Carrier and Flight      26  Issuing Tickets              
 7  Waitlisted and ARNK Segments       27  Advance Seat Assignment
 8  Name Element                       28  Queues                
 9  Contact Element                    29  Central Profiles     
10  Ticketing Element                  30  Reference Information    
11  Received-from Element              31  Hotel List Displays
12  Building a PNR                     32  Hotel Availability and Rates
13  Supplementary Data                 33  Hotel Features        
14  Optional Service Information       34  Selling Hotel Segments
15  Special Service Requests           35  Modifying Hotel Segments
16  Retrieving and Displaying PNRs     36  Car Availability and Rates 
17  Cancelling PNR Elements            37  Car Terms and Locations
18  Modifying PNR Elements             38  Selling Car Segments    
19  Changing Segment Status            39  Modifying Car Segments 
20  Splitting a PNR                    40  Miscellaneous Entries